name: test workflow
on: [push]
#Jobs that are part of workflow:
jobs:
  Test_Ex:
    #runs on ubuntu machine
    runs-on: ubuntu-latest
    steps:
    #command to get files on the ubuntu machine
    - name: Check out repo
      uses: actions/checkout@v3
    - run: touch testyaml.py
    - run: ls
  build_job:
    runs-on: ubuntu-latest
    steps:
    - name : check out repo
      uses: actions/checkout@v3
    - run: chmod + xbuildScript.sh 
    - run: ./buildScript.sh
    - run: ls
      
      

    
